In [5]:
import tensorflow
import numpy as np
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [6]:
model=Sequential()
model.add(SimpleRNN(3,input_shape=(4,5)))
model.add(Dense(1,activation='sigmoid'))

In [7]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 3)              │            27 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31 (124.00 B)

 Trainable params: 31 (124.00 B)

 Non-trainable params: 0 (0.00 B)

In [8]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 3)


array([[ 0.4367836 ,  0.04098725,  0.5709364 ],
       [ 0.13374269, -0.79998696, -0.71342003],
       [ 0.43870646, -0.6082448 ,  0.01142949],
       [ 0.1699    ,  0.11548334,  0.05478299],
       [-0.6928886 , -0.18919176,  0.8452999 ]], dtype=float32)

In [9]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(3, 3)


array([[-0.27539682,  0.29353833,  0.91541904],
       [-0.7410752 , -0.6713784 , -0.00766259],
       [ 0.61234325, -0.6805046 ,  0.40242925]], dtype=float32)

In [10]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(3,)


array([0., 0., 0.], dtype=float32)