In [3]:
import tensorflow
import numpy as np
import pandas as pd
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,SimpleRNN

In [12]:
model=Sequential()
model.add(SimpleRNN(4,input_shape=(4,5)))
model.add(Dense(1,activation='relu'))
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)        │ (None, 4)              │            40 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             5 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 45 (180.00 B)

 Trainable params: 45 (180.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
print(model.get_weights()[0].shape)
model.get_weights()[0]

(5, 4)


array([[-0.1566894 ,  0.5736908 , -0.46159568,  0.5350754 ],
       [ 0.66965055,  0.01121366,  0.2779851 ,  0.5562757 ],
       [ 0.01267368, -0.5756624 , -0.32171917,  0.6743746 ],
       [-0.07556677,  0.53300774,  0.3522892 , -0.05968249],
       [ 0.29831326, -0.12239593, -0.2258851 ,  0.0672093 ]],
      dtype=float32)

In [15]:
print(model.get_weights()[1].shape)
model.get_weights()[1]

(4, 4)


array([[-0.0215894 ,  0.34683746,  0.8107324 , -0.47111648],
       [ 0.8206269 ,  0.21675873,  0.21088833,  0.48488486],
       [ 0.5622745 , -0.14313108, -0.3509038 , -0.7350016 ],
       [ 0.0997638 , -0.90123963,  0.41845635,  0.05204361]],
      dtype=float32)

In [14]:
print(model.get_weights()[2].shape)
model.get_weights()[2]

(4,)


array([0., 0., 0., 0.], dtype=float32)