## Text Representaion

In [1]:
import pandas as pd
import numpy as np
# %pip install seaborn
import seaborn as sns
import matplotlib.pyplot as plt

## Bag of words

In [2]:
import pandas as pd

# Sample dataset
data = {
    'Review': [
        "I love this product",
        "This worst is the worst purchase I've made",
        "Absolutely fantastic  quality!",
        "Terrible experience, not recommended",
        "I'm very happy very with this",
        "Do not buy this, it's bad",
        "Excellent value for the money",
        "Worst product ever",
        "Very satisfied with the service",
        "I hate this hate so much"
    ],
    'Sentiment': [
        "positive",
        "negative",
        "positive",
        "negative",
        "positive",
        "negative",
        "positive",
        "negative",
        "positive",
        "negative"
    ]
}

df = pd.DataFrame(data)


In [3]:
df.head()

Review Sentiment
0                         I love this product  positive
1  This worst is the worst purchase I've made  negative
2              Absolutely fantastic  quality!  positive
3        Terrible experience, not recommended  negative
4               I'm very happy very with this  positive

In [4]:
# %pip install nltk
# %pip install scikit-learn
from sklearn.feature_extraction.text import CountVectorizer

In [5]:
cv=CountVectorizer()
bow=cv.fit_transform(df['Review'])

In [6]:
print(cv.vocabulary_)

{'love': 13, 'this': 27, 'product': 18, 'worst': 32, 'is': 11, 'the': 26, 'purchase': 19, 've': 29, 'made': 14, 'absolutely': 0, 'fantastic': 7, 'quality': 20, 'terrible': 25, 'experience': 6, 'not': 17, 'recommended': 21, 'very': 30, 'happy': 9, 'with': 31, 'do': 3, 'buy': 2, 'it': 12, 'bad': 1, 'excellent': 5, 'value': 28, 'for': 8, 'money': 15, 'ever': 4, 'satisfied': 22, 'service': 23, 'hate': 10, 'so': 24, 'much': 16}


In [7]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())
print(bow[3].toarray())
print(bow[4].toarray())
for i in range(len(bow.toarray())):
    print(bow[i].toarray())

[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 2]]
[[1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 1 0]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 2]]
[[1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 1 0]]
[[0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]]
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0]]
[[0 0 0 0 0 0 0 0 0 

In [8]:
# Bag of Words (BoW) is a simple and commonly used method for text representation in Natural Language Processing (NLP). It converts text documents into numerical feature vectors, which can then be used for various machine learning tasks. The basic idea is to represent each document as a vector of word counts or binary values, indicating the presence or absence of words in the document
for i in range(len(bow.toarray())):
    print(bow[i].toarray())


[[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 0 2]]
[[1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 2 1 0]]
[[0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]]
[[0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0]]
[[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]
[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 0]]
[[0 0 0 0 0 0 0 0 0 0 2 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0]]


### N-grams

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(ngram_range=(3,3))
bow = cv.fit_transform(df['Review'])
print(cv.vocabulary_)
print(len(cv.vocabulary_))

{'love this product': 10, 'this worst is': 18, 'worst is the': 24, 'is the worst': 9, 'the worst purchase': 15, 'worst purchase ve': 26, 'purchase ve made': 12, 'absolutely fantastic quality': 0, 'terrible experience not': 14, 'experience not recommended': 4, 'very happy very': 20, 'happy very with': 6, 'very with this': 22, 'do not buy': 2, 'not buy this': 11, 'buy this it': 1, 'this it bad': 17, 'excellent value for': 3, 'value for the': 19, 'for the money': 5, 'worst product ever': 25, 'very satisfied with': 21, 'satisfied with the': 13, 'with the service': 23, 'hate this hate': 8, 'this hate so': 16, 'hate so much': 7}
27


### TF-IDF

In [22]:
# Sample documents
docs = [
    "People wathch anime",
    "anime watch anime",
    "People wite comment",
    "anime write anime"
]
doc=pd.DataFrame(docs, columns=['text'])

doc.head()

text
0  People wathch anime
1    anime watch anime
2  People wite comment
3    anime write anime

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

tf_idf = tfidf.fit_transform(doc['text'])
print(tf_idf.toarray())

[[0.44809973 0.         0.55349232 0.         0.70203482 0.
  0.        ]
 [0.78722298 0.         0.         0.61666846 0.         0.
  0.        ]
 [0.         0.61761437 0.48693426 0.         0.         0.61761437
  0.        ]
 [0.78722298 0.         0.         0.         0.         0.
  0.61666846]]


In [30]:
x=pd.DataFrame(tf_idf.toarray(), columns=tfidf.get_feature_names_out())
print(x)

      anime   comment    people     watch    wathch      wite     write
0  0.448100  0.000000  0.553492  0.000000  0.702035  0.000000  0.000000
1  0.787223  0.000000  0.000000  0.616668  0.000000  0.000000  0.000000
2  0.000000  0.617614  0.486934  0.000000  0.000000  0.617614  0.000000
3  0.787223  0.000000  0.000000  0.000000  0.000000  0.000000  0.616668


In [ ]:
print(tfidf.idf_)
print(tfidf.vocabulary_)
print(tfidf.tf)

[1.22314355 1.91629073 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073]
{'people': 2, 'wathch': 4, 'anime': 0, 'watch': 3, 'wite': 5, 'comment': 1, 'write': 6}
[1.22314355 1.91629073 1.51082562 1.91629073 1.91629073 1.91629073
 1.91629073]
