In [1]:
import pandas as pd
import numpy as np
# %pip install wget
# %pip install --upgrade gensim

In [4]:
import gensim
from gensim.models import Word2Vec,keyedvectors
import wget


### Pretained word2vec model

#### we will use the pre-trained weights of word2vec that was trained on google New corpus containing 3 billio words.This model consists og 300-dimensional vectors for 3 million and phrases.

In [ ]:
# Pretained word2vec model

In [14]:
%pip install kagglehub
import kagglehub

# Download latest version
path = kagglehub.dataset_download("adarshsng/googlenewsvectors")

print("Path to dataset files:", path)

  Using cached kagglehub-0.3.11-py3-none-any.whl.metadata (32 kB)
  Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl.metadata (2.1 kB)
  Using cached requests-2.32.3-py3-none-any.whl.metadata (4.6 kB)
  Using cached charset_normalizer-3.4.1-cp312-cp312-win_amd64.whl.metadata (36 kB)
  Using cached idna-3.10-py3-none-any.whl.metadata (10 kB)
  Using cached urllib3-2.4.0-py3-none-any.whl.metadata (6.5 kB)
  Using cached certifi-2025.1.31-py3-none-any.whl.metadata (2.5 kB)
Using cached kagglehub-0.3.11-py3-none-any.whl (63 kB)
Using cached PyYAML-6.0.2-cp312-cp312-win_amd64.whl (156 kB)
Using cached requests-2.32.3-py3-none-any.whl (64 kB)
Using cached certifi-2025.1.31-py3-none-any.whl (166 kB)
Using cached charset_normalizer-3.4.1-cp312-cp312-win_amd64.whl (102 kB)
Using cached idna-3.10-py3-none-any.whl (70 kB)
Using cached urllib3-2.4.0-py3-none-any.whl (128 kB)
Note: you may need to restart the kernel to use updated packages.


d:\Programming\Deep_Learning\.deeplr\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


100%|██████████| 1.64G/1.64G [06:34<00:00, 4.46MB/s]

Extracting files...


Path to dataset files: C:\Users\sande\.cache\kagglehub\datasets\adarshsng\googlenewsvectors\versions\1


In [16]:
import os
print("Files in dataset directory:", os.listdir(path))
# Load the model
model = gensim.models.KeyedVectors.load_word2vec_format(path + '/GoogleNews-vectors-negative300.bin', binary=True)

Files in dataset directory: ['GoogleNews-vectors-negative300.bin']


In [18]:
model['computer']  # get the vector for the word 'computer'
model['man'].shape  # check the shape of the vector

(300,)

In [19]:
model['woman']

array([ 2.43164062e-01, -7.71484375e-02, -1.03027344e-01, -1.07421875e-01,
        1.18164062e-01, -1.07421875e-01, -1.14257812e-01,  2.56347656e-02,
        1.11816406e-01,  4.85839844e-02, -9.71679688e-02, -3.43750000e-01,
       -6.29882812e-02, -1.25000000e-01, -2.70996094e-02,  9.42382812e-02,
       -1.87500000e-01, -5.34667969e-02,  6.25000000e-02, -3.05175781e-02,
       -2.90527344e-02, -4.80957031e-02, -5.51757812e-02, -4.08203125e-01,
        1.01318359e-02, -2.32421875e-01, -1.70898438e-01,  2.63671875e-01,
        3.49609375e-01, -2.11914062e-01,  1.43554688e-01, -6.22558594e-03,
       -2.25585938e-01, -1.05468750e-01, -1.16210938e-01,  1.23046875e-01,
        3.06640625e-01, -4.88281250e-02, -9.57031250e-02,  1.99218750e-01,
       -1.57226562e-01, -2.80761719e-02,  1.58203125e-01, -2.42919922e-02,
        1.29882812e-01, -8.98437500e-02, -7.61718750e-02,  3.54003906e-02,
       -3.06396484e-02,  1.52343750e-01,  5.24902344e-02,  1.60980225e-03,
        5.56640625e-02,  

In [20]:
model['woman'].shape  # get the vector for the word

(300,)

In [21]:
model['cricket']

array([-3.67187500e-01, -1.21582031e-01,  2.85156250e-01,  8.15429688e-02,
        3.19824219e-02, -3.19824219e-02,  1.34765625e-01, -2.73437500e-01,
        9.46044922e-03, -1.07421875e-01,  2.48046875e-01, -6.05468750e-01,
        5.02929688e-02,  2.98828125e-01,  9.57031250e-02,  1.39648438e-01,
       -5.41992188e-02,  2.91015625e-01,  2.85156250e-01,  1.51367188e-01,
       -2.89062500e-01, -3.46679688e-02,  1.81884766e-02, -3.92578125e-01,
        2.46093750e-01,  2.51953125e-01, -9.86328125e-02,  3.22265625e-01,
        4.49218750e-01, -1.36718750e-01, -2.34375000e-01,  4.12597656e-02,
       -2.15820312e-01,  1.69921875e-01,  2.56347656e-02,  1.50146484e-02,
       -3.75976562e-02,  6.95800781e-03,  4.00390625e-01,  2.09960938e-01,
        1.17675781e-01, -4.19921875e-02,  2.34375000e-01,  2.03125000e-01,
       -1.86523438e-01, -2.46093750e-01,  3.12500000e-01, -2.59765625e-01,
       -1.06933594e-01,  1.04003906e-01, -1.79687500e-01,  5.71289062e-02,
       -7.41577148e-03, -

In [22]:
model.most_similar('man')

[('cricketing', 0.8372225761413574),
 ('cricketers', 0.8165745735168457),
 ('Test_cricket', 0.8094819188117981),
 ('Twenty##_cricket', 0.8068488240242004),
 ('Twenty##', 0.7624265551567078),
 ('Cricket', 0.75413978099823),
 ('cricketer', 0.7372578382492065),
 ('twenty##', 0.7316356897354126),
 ('T##_cricket', 0.7304614186286926),
 ('West_Indies_cricket', 0.6987985968589783)]

In [24]:
model.most_similar('man', topn=5)  # find the most similar words to 'computer'

[('woman', 0.7664012908935547),
 ('boy', 0.6824871301651001),
 ('teenager', 0.6586930155754089),
 ('teenage_girl', 0.6147903203964233),
 ('girl', 0.5921714305877686)]

In [25]:
model.most_similar('facebook')

[('Facebook', 0.7563533186912537),
 ('FaceBook', 0.7076998949050903),
 ('twitter', 0.6988552212715149),
 ('myspace', 0.6941817998886108),
 ('Twitter', 0.664244532585144),
 ('twitter_facebook', 0.6572229862213135),
 ('Facebook.com', 0.6529868245124817),
 ('myspace_facebook', 0.6370643973350525),
 ('facebook_twitter', 0.6367618441581726),
 ('linkedin', 0.6356592774391174)]

In [26]:
model.similarity('computer', 'laptop')  # find the similarity between 'computer' and 'laptop'

0.66404927

In [32]:
model.similarity('man','woman') # find the similarity between 'computer' and 'car'

0.76640123

In [33]:
model.similarity('man','java')

0.019312032

In [35]:
model.doesnt_match(['PHP', 'Python', 'monkey', 'C++'])  # find the word that doesn't match with the others

'monkey'

In [39]:
vec=model['king']-model['man']+model['woman']  # create
model.most_similar([vec])  # find the most similar word to the vector

[('king', 0.8449392318725586),
 ('queen', 0.7300517559051514),
 ('monarch', 0.645466148853302),
 ('princess', 0.6156251430511475),
 ('crown_prince', 0.5818676352500916),
 ('prince', 0.5777117609977722),
 ('kings', 0.5613663792610168),
 ('sultan', 0.5376775860786438),
 ('Queen_Consort', 0.5344247817993164),
 ('queens', 0.5289887189865112)]

In [40]:
vec=model['INR']-model['India']+model['USA']  # create a vector for 'USA'
model.most_similar([vec])  # find the most similar word to the vector

[('INR', 0.6742157340049744),
 ('EUR', 0.47155696153640747),
 ('USD', 0.4371035695075989),
 ('CHF', 0.4333430528640747),
 ('approx', 0.4275132417678833),
 ('#,###.##_PER_GBP', 0.4238359034061432),
 ('GBP', 0.41852837800979614),
 ('Eur', 0.41400232911109924),
 ('PERLANE', 0.4124673306941986),
 ('##,###.##_DENOMINATION', 0.40693598985671997)]

In [43]:
model['robot']

array([-4.29687500e-02,  1.02050781e-01, -4.17480469e-02,  3.36914062e-02,
       -4.27246094e-02, -8.54492188e-03,  9.37500000e-02,  1.10839844e-01,
        6.73828125e-02, -4.55078125e-01, -1.37939453e-02,  6.34765625e-02,
        1.68945312e-01, -1.78710938e-01,  1.53808594e-02,  1.21093750e-01,
       -2.34375000e-01, -2.36511230e-03,  2.07519531e-02, -1.88476562e-01,
        1.71875000e-01,  9.81445312e-02, -4.32128906e-02,  1.24511719e-01,
       -1.43554688e-01,  5.54199219e-02, -1.50390625e-01,  6.98242188e-02,
        1.68457031e-02, -1.02539062e-01, -1.10839844e-01, -2.81250000e-01,
       -1.92382812e-01,  1.54418945e-02, -2.58789062e-02, -2.41210938e-01,
       -3.63769531e-02,  2.50000000e-01, -1.44653320e-02, -3.19824219e-02,
        4.33349609e-03, -1.89453125e-01,  1.70898438e-01,  4.96093750e-01,
       -9.08203125e-02, -1.52343750e-01,  4.58984375e-02,  1.37695312e-01,
        3.35937500e-01, -1.01562500e-01, -3.69140625e-01, -2.23388672e-02,
        2.22167969e-02, -